- .gitignore
- features/step_definitions/steps.rb
- features/support/env.rb
- features/user_management/basic_user_accounts.feature
> 5 basic user accounts

- features/decide/click_on_broadcasts.feature
- features/filter/number_of_filtered_broadcasts.feature
- features/step_definitions/steps.rb
> 6 click on broadcasts

- Gemfile.lock
- features/filter/number_of_filtered_broadcasts.feature
- features/invoice/generate_invoices.feature
- features/step_definitions/steps.rb
- features/support/env.rb
> 9 generate invoices

- .gitmodules
- Gemfile.lock
- features/decide/pagination.feature
- features/step_definitions/steps.rb
> 13 pagination

- features/invoice/change_amount.feature
- features/invoice/unselect_broadcast.feature
- features/step_definitions/steps.rb
> 18 change amount

- features/invoice/see_leftover_budget.feature
- features/step_definitions/steps.rb
> 20 see leftover budget

- features/step_definitions/steps.rb
- features/user_management/basic_user_accounts.feature
> Semantic ui

- features/language/language_chooser_menu.feature
- features/step_definitions/steps.rb
> 23 language chooser menu

- features/invoice/release_amount.feature
- features/step_definitions/steps.rb
> 26 release fixed amount

- .gitignore
- Gemfile.lock
- features/balances/total_amount_collected.feature
- features/landing_page/explain_the_purpose.feature
- features/step_definitions/steps.rb
- features/user_management/basic_user_accounts.feature
> 28 public balances

- .travis.yml
- features/decide/click_on_broadcasts.feature
- features/decide/one_broadcast_at_a_time.feature
- features/decide/reload_broadcasts.feature
- features/step_definitions/steps.rb
- features/support/wait.rb
> 34 display only one broadcast at a time

- features/landing_page/stats.feature
- features/step_definitions/steps.rb
> 36 show some stats

- features/decide/back_button.feature
- features/decide/reload_broadcasts.feature
- features/landing_page/explain_the_purpose.feature
- features/step_definitions/steps.rb
> 46 back button

- features/decide/create_missing_broadcast.feature
- features/step_definitions/steps.rb
> 35 create missing records

- Gemfile.lock
- features/decide/search.feature
- features/step_definitions/steps.rb
> 33 search broadcasts by title

- features/balances/better_metrics.feature
- features/balances/total_amount.feature
- features/step_definitions/steps.rb
> 63 better metrics

- features/decide/new/validate_broadcast.feature
- features/step_definitions/steps.rb
> 60 broadcast validations

- features/broadcasts/reselect_broadcast.feature
- features/step_definitions/steps.rb
> 54 reselect broadcasts

- features/decide/medium.feature
- features/step_definitions/steps.rb
> 43 label tv or radio

- features/decide/filter_by_medium.feature
- features/step_definitions/steps.rb
> 79 filter by medium

- features/decide/filter_by_medium.feature
- features/step_definitions/steps.rb
change filters from button to multi-select box, simplify code
> Refactoring filter

- features/broadcasts/change_attributes.feature
- features/step_definitions/steps.rb
> 86 change attributes retrospectively

- features/step_definitions/steps.rb
- features/user_management/basic_user_accounts.feature
- features/user_management/guest_user.feature
> 30 cache write requests for guests

- features/balances/sorting.feature
- features/balances/total_amount.feature
- features/step_definitions/steps.rb
> 99 sort balances

- .travis.yml
- features/decide/back_button.feature
- features/decide/create_missing_broadcast.feature
- features/decide/guidance.feature
- features/decide/reload_broadcasts.feature
- features/landing_page/explain_the_purpose.feature
- features/landing_page/stats.feature
- features/step_definitions/steps.rb
- features/user_management/guest_user.feature
> 38 guide through process

- Gemfile.lock
- features/broadcasts/reselect_broadcast.feature
- features/decide/create_missing_broadcast.feature
- features/decide/filter_by_medium.feature
- features/decide/filter_by_station.feature
- features/decide/medium.feature
- features/step_definitions/steps.rb
> 102 filter by station

- features/decide/filter_by_station.feature
- features/decide/station.feature
- features/step_definitions/steps.rb
> 109 110 order stations and display name

- features/decide/filter_by_station.feature
- features/step_definitions/steps.rb
> 116 unselect filter options

- features/decide/back_button.feature
- features/decide/click_on_broadcasts.feature
- features/decide/create_missing_broadcast.feature
- features/decide/guidance.feature
- features/decide/one_broadcast_at_a_time.feature
- features/decide/reload_broadcasts.feature
- features/step_definitions/steps.rb
- features/user_management/guest_user.feature
- frontend/tests/integration/components/decision-card-test.js
- frontend/translations/de.yaml
- frontend/translations/en.yaml
close #125
@somamo review please - changed the button labels
> better labels for buttons

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
- Procfile
- ProcfileTesting
- README.md
- features/support/env.rb
> remove exhaust with specialized travis.yml

- frontend/app/router.js
- frontend/app/routes/data-privacy.js
- frontend/app/templates/application.hbs
- frontend/app/templates/data-privacy.hbs
- frontend/tests/unit/routes/data-privacy-test.js
- frontend/translations/de.yaml
- frontend/translations/en.yaml
> created route /data-privacy and copy pasted data privacy statement

- features/landing_page/explain_the_purpose.feature
- frontend/app/styles/app.css
- frontend/app/templates/index.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
In this pull request the layout is centred. 
Robert and me have discussed to try out a left aligned design. So how do you like this proposal?
> Improve start content

- frontend/app/routes/login.js
> fix the awful async problem during authentication

- .travis.yml
- auth0/emails/passwordless.html
- features/user_management/guest_user.feature
- frontend/app/authenticators/stub-authenticator.js
- frontend/app/controllers/decide.js
- frontend/app/routes/application.js
- frontend/config/environment.js
- frontend/package.json
- frontend/tests/integration/components/decision-card-deck-next-step-test.js
- frontend/translations/de.yaml
- frontend/translations/en.yaml
close #106 
close #112  
You can check the full documentation here: https://github.com/auth0/lock-passwordless
> Redirect passwordless

- backend/spec/requests/balances_spec.rb
> expose #144

- .travis.yml
should deal with #136 or at least show the proper error message on travis
> use ember deploy on travis

- frontend/app/templates/index.hbs
- frontend/package.json
@somamo could you have a look?
> add embedded twitter timeline

- ProcfileTesting
- README.md
- backend/Gemfile
- backend/config/database.travis.yml
- backend/config/database.yml
- backend/config/environments/fullstack.rb
- backend/config/initializers/knock.rb
- backend/config/secrets.yml
- features/support/env.rb
- frontend/config/environment.js
Closes #228
@arun1595 @mattlindsey just one environment for fullstack testing!
@arun1595 if the build passes, could you merge this, please?
> custom fullstack environment for backend and frontend, dry secrets.yml

- Gemfile.lock
- backend/Gemfile.lock
> update backend dependencies

- frontend/tests/integration/components/broadcast-form-modal-test.js
- frontend/tests/integration/components/broadcast-form-test.js
- frontend/tests/integration/components/broadcast-search-test.js
- frontend/tests/integration/components/decision-card-test.js
- frontend/tests/integration/components/fa-question-test.js
- frontend/tests/integration/components/find-broadcasts/navigation-test.js
- frontend/tests/integration/components/geo/info-box-test.js
- frontend/tests/integration/components/invoice-footer-test.js
- frontend/tests/integration/components/invoice-item-test.js
- frontend/tests/integration/components/missing-feature-test.js
> fix ember-intl warnings

- features/step_definitions/steps.rb
- frontend/app/templates/index.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
> show cloze as explanation of the differences to tv ratings

- frontend/app/controllers/find-broadcasts.js
- frontend/config/environment.js
- frontend/tests/acceptance/broadcast/navigation-test.js
- frontend/tests/acceptance/find-broadcasts/search-resets-pagination-test.js
- frontend/tests/acceptance/update-location-test.js
> 262 search resets pagination

- frontend/app/templates/components/visualize/diff/chart-explanation.hbs
- frontend/app/templates/visualize/diff.hbs
- frontend/app/templates/visualize/diff/loading.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
> more visible chart explanations

- frontend/app/routes/application.js
- frontend/tests/acceptance/preferred-language-test.js
> [WIP] expose #283

- frontend/app/models/invoice.js
- frontend/tests/unit/models/invoice-test.js
round difference between desiredAmount and currentAmount to manage javascript number precision and have the expected exact difference
> Round difference between desiredAmount and currentAmount to 2 decimals

- backend/app/controllers/broadcasts_controller.rb
- backend/app/models/broadcast.rb
- backend/spec/models/broadcast_spec.rb
- backend/spec/requests/broadcasts/full_text_search_spec.rb
> 288 fix search and filter at same time

- backend/app/controllers/broadcasts_controller.rb
- features/find-broadcasts/search/search.feature
- features/step_definitions/steps.rb
This PR adds a feature scenario to test ordering together with fulltext search
fixes #301
> Fix Bug 301 Sorting has no effect in search

- backend/app/controllers/broadcasts_controller.rb
- backend/app/models/broadcast.rb
- backend/spec/models/broadcast_spec.rb
Moved the search logic from controller to Broadcast model, where it is easier to test.
> Refactor broadcast search

- .travis.yml
- Gemfile.lock
- backend/Gemfile
- backend/Gemfile.lock
- backend/app/controllers/broadcasts_controller.rb
- backend/app/models/broadcast.rb
- backend/app/serializers/broadcast_serializer.rb
- backend/db/migrate/20171021173446_add_broadcast_url_to_broadcasts.rb
- backend/db/schema.rb
- backend/spec/models/broadcast_spec.rb
- backend/spec/rails_helper.rb
- backend/spec/requests/broadcasts_spec.rb
- backend/spec/support/api/schemas/broadcast.json
- features/find-broadcasts/detail_view.feature
- features/step_definitions/steps.rb
- frontend/app/models/broadcast.js
- frontend/app/templates/components/broadcast/broadcast-details.hbs
- frontend/app/templates/components/broadcast/broadcast-form.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
> 352 link to broadcast

- README.md
Close #341 
Done:
-  instructions for setting up graphviz
- make the setting up commands more obvious
The setup instructions are now numbered and more explained as to why we are doing each step
> Add: instructions for setting up graphviz

- .travis.yml
- backend/app/models/broadcast.rb
- backend/app/models/impression.rb
- backend/db/migrate/20171111141249_update_statistic_broadcasts_to_version_4.rb
- backend/db/schema.rb
- backend/db/views/statistic_broadcasts_v04.sql
> add statistic_broadcasts materialized view

- frontend/tests/integration/components/geo/update-location-test.js
- frontend/translations/de.yaml
- frontend/translations/en.yaml
changes in two file for login lable changes for bug #267 
Edit: fix #267
> Communicate passwordless login

- backend/Gemfile
- backend/Gemfile.lock
- backend/app/controllers/application_controller.rb
- backend/config/application.rb
- backend/config/initializers/sentry.rb
This sets up error reporting for the backend, see #380
> Set up sentry for backend

- frontend/app/routes/application.js
- frontend/config/environment.js
- frontend/package.json
- frontend/yarn.lock
Close #380 
This enables error reporting for the frontend.
> Error reporting

- frontend/app/templates/statistics.hbs
in order to check out the description and support the broadcast
close #429
> Link to broadcast page

- backend/app/controllers/statistic/broadcasts_controller.rb
- backend/spec/requests/statistic/broadcast_spec.rb
- frontend/app/templates/statistics.hbs
Close #431 
Thanks @davidak for noticing. This should fix it.
> 431 average null values

- frontend/app/templates/data-privacy.hbs
> Mention and explain Auth0 in data privacy section

- backend/app/controllers/statistic/broadcasts_controller.rb
- backend/app/models/ability.rb
- backend/config/routes.rb
- backend/spec/models/statistic/broadcast/history_spec.rb
- backend/spec/rails_helper.rb
- backend/spec/requests/statistic/broadcast_spec.rb
> Backend sends historical statistic data for a given broadcast

- frontend/app/components/error-frown.js
- frontend/app/components/loading-spinner.js
- frontend/app/routes/index.js
- frontend/app/templates/components/error-frown.hbs
- frontend/app/templates/components/loading-spinner.hbs
- frontend/app/templates/error.hbs
- frontend/app/templates/index.hbs
- frontend/app/templates/loading.hbs
- frontend/package.json
- frontend/tests/integration/components/error-frown-test.js
- frontend/tests/integration/components/loading-spinner-test.js
- frontend/yarn.lock
Setup ember concurrency to show landing page faster.
> Skeleton screens

- backend/app/models/statistic/broadcast.rb
- backend/spec/models/statistic/broadcast_spec.rb
> 343 broadcasts by area

- backend/app/models/similarity.rb
- frontend/app/components/visualize/graph/graph-visualization.js
- frontend/app/controllers/visualize/graph.js
- frontend/app/routes/visualize/graph.js
- frontend/app/templates/components/visualize/graph/graph-visualization.hbs
- frontend/app/templates/visualize/graph.hbs
- frontend/tests/unit/routes/visualize/graph-test.js
- frontend/translations/de.yaml
- frontend/translations/en.yaml
- frontend/yarn.lock
[WIP] Adding button to frontend so that authenticated users can toggle between visualizing all similarities and only similarities related to their liked broadcasts.
Problems that need to be fixed:
- requests are not passing authentication. current_user in backend is always nil
- the page is not refreshed after the button is clicked, but the url is updated and the new request reaches the backend
- the button should be disabled if the user is not authenticated
- the button should show "active" style when you are visualizing specif_to_user data
- add frontend tests
> 615 show user specific broadcast similarities

- frontend/app/templates/about-us.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
cc @sigu @mattlindsey @somamo 
Feel free to add your description @faithngetich @Kachulio1 @domangi @aonomike @ZmagoD @mz99 @tbaraza @lbmorales @maryam21 @adityavarma1234 @mattwr18
> Update about-us page

- frontend/app/components/visualize/bubble-chart-legend.js
- frontend/app/components/visualize/bubble-chart.js
- frontend/app/components/visualize/graph/graph-visualization.js
- frontend/config/environment.js
This allows us to import 3rd party plugins
> D3 dont use global import

- frontend/app/controllers/visualize/diff/media.js
- frontend/app/controllers/visualize/diff/stations.js
- frontend/app/router.js
- frontend/package.json
- frontend/yarn.lock
* Remove own imports of { copy }
* Update ember-metrics to current git master branch
> Fix ember-copy deprecation

- frontend/app/templates/index.hbs
in order to give credit to the open source community.
> Add YouTube playlist with meetings

- frontend/app/styles/app.css
- frontend/app/templates/index.hbs
- frontend/translations/de.yaml
- frontend/translations/en.yaml
To youtube playlist on our landing page. @lindseyperry have a look in "Files changed".
@mattwr18 I was considering to add a youtube placeholder with a clickable link for data privacy. Similar to the twitter button below. We could use a thumbnail of a video. Does that sound like an idea?
> Embedded Youtube Video on Start Page: Add a description and translations

- README.md
Fixes #931
Updated readme file
It was impossible to seed the local database without running redis server
> Readme updated with info about running redis

- frontend/package.json
- frontend/yarn.lock
Reverts roschaefer/rundfunk-mitbestimmen#944
> Revert "Bump ember-fetch from 6.1.0 to 6.2.1 in /frontend"

- frontend/app/components/visualize/bubble-chart.js
- frontend/app/controllers/visualize/time/index.js
changed way the array is calculated and passed to the bubble chart domain method
Fixes #979  - Without real data it's hard to test it
I have no idea how to test it in ember - I'll probably can extract this into variable and create an unit test. Any suggestions welcome
> use quadrille function chroma.limits to pass params to domain

- frontend/package.json
- frontend/yarn.lock
Get rid of security vulnerabilities
> Remove ember-cli-release
